# Generated by Django 5.0.1 on 2024-09-29 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=20, unique=True)),
                ("item_name", models.CharField(max_length=100)),
                ("customer_details", models.TextField()),
                ("order_date", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("return_reason", models.CharField(max_length=255)),
                (
                    "return_tracking",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Requested"),
                            (1, "Processing"),
                            (2, "Pickup Scheduled"),
                            (3, "Pickup Completed"),
                            (4, "Canceled"),
                            (5, "Refund Completed"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="disputes.order"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Dispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "dispute_reason_type",
                    models.SmallIntegerField(
                        choices=[(0, "Billing"), (1, "Service"), (2, "Other")]
                    ),
                ),
                ("dispute_reason_description", models.TextField()),
                (
                    "status",
                    models.SmallIntegerField(choices=[(0, "Open"), (1, "Resolved")]),
                ),
                ("resolution", models.TextField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="disputes.order"
                    ),
                ),
                (
                    "return_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="disputes.return",
                    ),
                ),
            ],
        ),
    ]
